### PR TITLE
Fixes cucumber expression. Adds tests based on current build. Resolves #14

### LINKED ISSUE #14: expressions evaluation behaves unexpectedly
First, I would like to thank you for the initiative on keeping the same development experience between the cucumber test runner and jest as I believe this brings the best of both worlds.

Now, whenever using two variables _(or more)_ in the same sentence with `{string} and {string}` the first one is repeated as the second where the first one passed wrapped in quotes?

```cucumber
# test.feature
Feature:
    Scenario:
	When I say "foo" and "bar"
```

The test below passes but should fail as bar is expected to be `bar` and foo is expected to be `foo` and not `"foo"`

```js
// test.steps.js
const { When } = require('@cucumber/cucumber');

When('I say {string} and {string}', function (foo, bar) {
    expect(bar).toBe('foo'); // bar should be bar
    expect(foo).toBe('"foo"'); // foo shouldn't be wrapped in quotes
});
```
When changing the test above to `{word} and {string}` the variables are both passed correctly, although, still wrapped in quotes?

```js
// test.steps.js
When('I say {word} and {string}', function (foo, bar) {
    expect(bar).toBe('"bar"'); // bar shouldn't be wrapped in quotes
    expect(foo).toBe('"foo"'); // foo shouldn't be wrapped in quotes
});

```

Perhaps [@cucumber/cucumber-expressions](https://www.npmjs.com/package/@cucumber/cucumber-expressions) could facilitate this integration?

_Another test case to investigate_
```js
// When I say "foo" and "bar" and "baz"
When('I say {string} and {string} and {string}', function (foo, bar, baz) {
    console.log(foo, bar, baz); // "foo" foo undefined
});
```

### PR DESCRIPTION
**Pull request by kevincmanning**

### CODE REVIEW

**Comment by mainfraame** [comment]
@kevincmanning ill take a look at this tonight. Thanks so much for your contribution

**Comment by kevincmanning** [comment]
@mainfraame No rush. I think I will add a couple more tests sometime today to make sure it still works with regex and not just cucumber expressions.

**Comment by kevincmanning** [comment]
@mainfraame ok I think this is in a state where it can be reviewed. please let me know if you have suggestions or concerns

**Comment by mainfraame** [comment]
Sorry, @kevincmanning, I completely forgot about your PR. I've been very busy with work and some family obligations. I've got free time tonight, I'll review it and get it merged. I'll also follow up with a comment to let you know once it's published.

File: src/parsers/steps.ts [hunk 1]
```diff
@@ -50,9 +50,9 @@ export function parseSteps(steps, definitions) {
             }
 
             const stepArgs = [
-                ...Array.from(
-                    definition.expression?.regexp?.exec(step.text) || []
-                ).slice(1),
+                ...definition.expression
```
Comment (mainfraame) [inline src/parsers/steps.ts:53]: I'll add a nullish coalesce here since spread operator on an array will throw an error when the spread value is undefined / null.

https://github.com/tc39/ecma262/issues/687

File: jest.config.ts [hunk 2]
```diff
@@ -0,0 +1,94 @@
+/*
+ * For a detailed explanation regarding each configuration property and type check, visit:
+ * https://jestjs.io/docs/en/configuration.html
+ */
+
+export default {
+    // Automatically clear mock calls and instances between every test
```
Comment (mainfraame) [inline jest.config.ts:7]: I'll also remove commented out code here.

**Review by mainfraame — APPROVED** [review]
@kevincmanning looks good to me. Did you try running the example tests against your changes?
